-- Tabela de dados de recebíveis (aba Recebíveis do Faturamento)
CREATE TABLE public.receivables_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL UNIQUE,
    -- Conta Bancária
    recebido_itau_debito DECIMAL(10,2) DEFAULT 0,
    recebido_itau_credito DECIMAL(10,2) DEFAULT 0,
    recebido_itau_pix DECIMAL(10,2) DEFAULT 0,
    deposito_dinheiro DECIMAL(10,2) DEFAULT 0,
    -- Adquirência
    recebido_rede_debito_bruto DECIMAL(10,2) DEFAULT 0,
    recebido_rede_credito_bruto DECIMAL(10,2) DEFAULT 0,
    taxa_tarifa DECIMAL(10,2) DEFAULT 0,
    recebido_total_liquido DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.receivables_data IS 'Dados da aba Recebíveis: Conta Bancária (Itaú) e Adquirência (Rede)';
COMMENT ON COLUMN public.receivables_data.recebido_itau_debito IS 'Recebido Itaú - Débito';
COMMENT ON COLUMN public.receivables_data.recebido_itau_credito IS 'Recebido Itaú - Crédito';
COMMENT ON COLUMN public.receivables_data.recebido_itau_pix IS 'Recebido Itaú - PIX';
COMMENT ON COLUMN public.receivables_data.deposito_dinheiro IS 'Depósito Dinheiro';
COMMENT ON COLUMN public.receivables_data.recebido_rede_debito_bruto IS 'Recebido Rede - Débito (Bruto)';
COMMENT ON COLUMN public.receivables_data.recebido_rede_credito_bruto IS 'Recebido Rede - Crédito (Bruto)';
COMMENT ON COLUMN public.receivables_data.taxa_tarifa IS 'Taxa/Tarifa';
COMMENT ON COLUMN public.receivables_data.recebido_total_liquido IS 'Recebido Total - Líquido';

CREATE INDEX idx_receivables_data_date ON receivables_data(data DESC);

CREATE TRIGGER update_receivables_data_updated_at
    BEFORE UPDATE ON receivables_data
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.receivables_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all select" ON public.receivables_data FOR SELECT USING (true);
CREATE POLICY "Allow all insert" ON public.receivables_data FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update" ON public.receivables_data FOR UPDATE USING (true);
CREATE POLICY "Allow all delete" ON public.receivables_data FOR DELETE USING (true);
