-- Tabela principal de dados de faturamento
CREATE TABLE public.billing_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL UNIQUE,
    abertura DECIMAL(10,2) DEFAULT 0,
    fechamento DECIMAL(10,2) DEFAULT 0,
    qtde_vendas INTEGER DEFAULT 0,
    dinheiro DECIMAL(10,2) DEFAULT 0,
    pix DECIMAL(10,2) DEFAULT 0,
    credito DECIMAL(10,2) DEFAULT 0,
    debito DECIMAL(10,2) DEFAULT 0,
    qr_code DECIMAL(10,2) DEFAULT 0,
    retirada DECIMAL(10,2) DEFAULT 0,
    transferencia DECIMAL(10,2) DEFAULT 0,
    debito_bruto DECIMAL(10,2) DEFAULT 0,
    debito_liquido DECIMAL(10,2) DEFAULT 0,
    credito_bruto DECIMAL(10,2) DEFAULT 0,
    credito_liquido DECIMAL(10,2) DEFAULT 0,
    debito_pos DECIMAL(10,2) DEFAULT 0,
    credito_pos DECIMAL(10,2) DEFAULT 0,
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_billing_data_date ON billing_data(data DESC);

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_billing_data_updated_at
    BEFORE UPDATE ON billing_data
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.billing_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all select" ON public.billing_data FOR SELECT USING (true);
CREATE POLICY "Allow all insert" ON public.billing_data FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update" ON public.billing_data FOR UPDATE USING (true);
CREATE POLICY "Allow all delete" ON public.billing_data FOR DELETE USING (true);